#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-A-1-1 --primary --mode 1920x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --rotate normal --left-of HDMI-A-1-1 &
nitrogen --set-zoom-fill --random ~/Wallpapers --head=0 &
nitrogen --set-zoom-fill --random ~/Wallpapers --head=1 &
picom &
pgrep -x polybar acer > /dev/null || polybar acer &
pgrep -x polybar phil > /dev/null || polybar phil &
ntfd &

bspc monitor HDMI-A-0 -d www dev chat
bspc monitor HDMI-A-1-1 -d sec rec 

bspc config border_width	2
bspc config window_gap 		12

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

